[project]
name = "aiogram-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
	"aiogram>=3.20.0.post0",
	"aiogram-i18n>=1.4",
	"aiosqlite>=0.21.0",
	"dotenv>=0.9.9",
	"sqlalchemy>=2.0.41",
]
